apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kubernetes-twistlock-controller
  name: kubernetes-twistlock-controller-health
  selfLink: /api/v1/namespaces/mgt-infra-controllers/services/kubernetes-twistlock-controller-health
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubernetes-twistlock-controller
    deploymentconfig: kubernetes-twistlock-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
