apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: etcd
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/rhel7/etcd:3.2.26
    generation: 1
    importPolicy: {}
    name: 3.2.26
    referencePolicy:
      type: Source
status:
  dockerImageRepository: docker-registry.default.svc:5000/etcd
